harnessApiVersion: '1.0'
type: BASIC
concurrencyStrategy: INFRA
envName: IIS-non-prod
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - duMEq8WxTRKZ4lgFSJykSg
phases:
- type: WINRM
  computeProviderName: Microsoft Azure Cloud Orchestration
  daemonSet: false
  infraDefinitionName: IIS Application
  name: Phase 1
  phaseSteps:
  - type: INFRASTRUCTURE_NODE
    name: Prepare Infra
    steps:
    - type: AWS_NODE_SELECT
      name: Select Nodes
      properties:
        excludeSelectedHostsFromFuturePhases: true
        instanceCount: 1
        specificHosts: false
    stepsInParallel: false
  - type: DISABLE_SERVICE
    name: Disable Service
    stepsInParallel: false
  - type: DEPLOY_SERVICE
    name: Deploy Service
    steps:
    - type: COMMAND
      name: Install
      properties:
        commandName: Install
    stepsInParallel: false
  - type: ENABLE_SERVICE
    name: Enable Service
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: S8 IIS Application
  statefulSet: false
rollbackPhases:
- type: WINRM
  computeProviderName: Microsoft Azure Cloud Orchestration
  daemonSet: false
  infraDefinitionName: IIS Application
  name: Rollback Phase 1
  phaseNameForRollback: Phase 1
  phaseSteps:
  - type: DISABLE_SERVICE
    name: Disable Service
    phaseStepNameForRollback: Enable Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: STOP_SERVICE
    name: Stop Service
    phaseStepNameForRollback: Deploy Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: DEPLOY_SERVICE
    name: Deploy Service
    phaseStepNameForRollback: Deploy Service
    statusForRollback: SUCCESS
    steps:
    - type: COMMAND
      name: Install
      properties:
        commandName: Install
    stepsInParallel: false
  - type: ENABLE_SERVICE
    name: Enable Service
    phaseStepNameForRollback: Disable Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    phaseStepNameForRollback: Deploy Service
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: S8 IIS Application
  statefulSet: false
templatized: false
